"""
ai_analysis_service.py
======================
Database service layer for persisted AI analyses.

Responsibilities
----------------
- Save a new analysis record generated by AIService.
- Retrieve the latest analysis for an investigation.
- Retrieve the full history list for an investigation.
"""
from __future__ import annotations

import logging
from typing import Any

from sqlalchemy.orm import Session

from app.models.ai_analysis import AIAnalysis

logger = logging.getLogger("kubesage.ai_analysis_service")


def save_analysis(
    db: Session,
    investigation_id: int,
    result: dict[str, Any],
) -> AIAnalysis:
    """
    Persist an AI analysis result to the database.

    Parameters
    ----------
    db : Session
        Active SQLAlchemy session.
    investigation_id : int
        The investigation this analysis belongs to.
    result : dict
        Dict returned by ``AIService.generate_summary()``.
        Expected keys: analysis, model, prompt_tokens, completion_tokens,
        duration_seconds.

    Returns
    -------
    AIAnalysis
        The newly created (and committed) ORM instance.
    """
    record = AIAnalysis(
        investigation_id=investigation_id,
        analysis=result["analysis"],
        model=result["model"],
        prompt_tokens=result.get("prompt_tokens"),
        completion_tokens=result.get("completion_tokens"),
        duration_seconds=result.get("duration_seconds"),
    )
    db.add(record)
    db.commit()
    db.refresh(record)

    logger.info(
        "Saved AI analysis | id=%d investigation_id=%d model=%s",
        record.id,
        investigation_id,
        record.model,
    )
    return record


def get_latest(db: Session, investigation_id: int) -> AIAnalysis | None:
    """Return the most recently created analysis for an investigation, or None."""
    return (
        db.query(AIAnalysis)
        .filter(AIAnalysis.investigation_id == investigation_id)
        .order_by(AIAnalysis.created_at.desc())
        .first()
    )


def get_history(db: Session, investigation_id: int) -> list[AIAnalysis]:
    """Return all analyses for an investigation, newest first."""
    return (
        db.query(AIAnalysis)
        .filter(AIAnalysis.investigation_id == investigation_id)
        .order_by(AIAnalysis.created_at.desc())
        .all()
    )
